### ISSUE TITLE
Unable to inject fragment widgets into Activity

### ISSUE THREAD

**Issue by djechelon** [dthommes/RoboSpring#1]
I have a very simple Activity class with a switch that is bound to Wifi power state. The activity uses a Fragment layout. I have annotated the `Switch` field with `@InjectView` but I ultimately end up in a `BeanCreationException` being unable to find the `View` with the given ID.

    public class MainActivity extends Activity {

	@InjectView
	private Switch activityMain_switchWifi;
	
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.layout_main);
		if (savedInstanceState == null) {
			getFragmentManager().beginTransaction()
					.add(R.id.container, new PlaceholderFragment()).commit();
		}
		
		RoboSpring.autowire(this);		
	}

This because the switch is declared within a Fragment

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context=".MainActivity$PlaceholderFragment" >

    <Switch
        android:id="@+id/activityMain_switchWifi"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentRight="true"
        android:layout_alignParentEnd="true"
        android:layout_alignParentTop="true"
        android:text="@string/fragment_main_txtWifiPower" />

    <LinearLayout
        android:id="@+id/activityMain_listWifis"
        android:layout_width="match_parent"
        android:layout_height="fill_parent"
        android:layout_below="@+id/activityMain_switchWifi"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="150dp"
        android:minHeight="300dp"
        android:paddingRight="15dp"
        android:paddingLeft="15dp"
        android:orientation="vertical" >
    </LinearLayout>

</RelativeLayout>
```

I have read on https://stackoverflow.com/questions/9780769/android-roboguice-inject-views-on-fragment that RoboGuice is supposed to inject views from fragment during the `onViewCreated()` method, but RoboSpring's `autowire` is usually called during `onCreate()` after setting the view.

I tried to `@InjectView` the view within the fragment, but obviously `autowire()` doesn't work if the target is not an `Activity`.

Am I learning RS wrong or is this a code issue? I have read the code and it basically calls a `findViewById` on the activity itself, which is obviously wrong for fragmented activities. I don't know what I'm doing wrong.

Thanks for support. I'm a RoboSpring beginner.

**Comment by dthommes** [comment]
Fixed in 1.0.7
