### ISSUE TITLE
applicationContext not found

### ISSUE THREAD

**Issue by OriolCrespo** [dthommes/RoboSpring#4]
Hi, I cannot make Android find my applicationContext, no matter where I add it. I have tried adding it to the src folder (file not found), to all the sub-folders, to the res folder (keeps complaining that filename cannot have uppercase letters), and to all sub-folders of res, but did not succeed. I have also tried to create a folder and add the resource manually (like in https://github.com/ajdev31/RoboSpringExt/blob/master/RoboSpringExample/build.gradle) but did not succeed either. Perhaps you could add to the Readme file how to configure the applicationContext file?

The application context not found error:

java.lang.RuntimeException: Unable to start activity ComponentInfo{...}: org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from class path resource [applicationContext.xml]; nested exception is java.io.FileNotFoundException: class path resource [applicationContext.xml] cannot be opened because it does not exist

Thank you in advance

**Comment by dthommes** [comment]
Hey,
sorry, the readme is from a time where I used ADT for Eclipse (didn't have the default directory structure of Gradle/Maven). I am not sure, whether RoboSpring still works with newer Android versions. Nonetheless, the `applicationContext.xml` file should be placed into the folder 

`src/main/resources`

as this is the default folder for Gradle to integrate the file into the Classpath. For your project, you have to create the `resources` folder (not `res` folder) to accomplish this.

_Please note:_ As of today, I don't recommend RoboSpring anymore. You may have a look for faster solutions that work with code generation for DI. You might find these useful:

https://github.com/google/dagger

https://docs.micronaut.io/latest/guide/index.html#android

-> The latter not being compatible with Android <= 6.0 and >= 9.0 at the moment.

**Comment by OriolCrespo** [comment]
Thank you very much, will do
